const BRANDS = {
  ACOPA: "Acopa",
  ALPIDEX: "Alpidex",
  ASAKUSA: "Asakusa",
  BLACK_DIAMOND: "Black Diamond",
  BOREAL: "Boreal",
  BUTORA: "Butora",
  CLIMB_X: "Climb X",
  CYPHER: "Cypher",
  EB: "EB",
  EVOLV: "Evolv",
  FIVE_TEN: "Five Ten",
  GARRA: "Garra",
  JURAX: "Jurax",
  LA_SPORTIVA: "La Sportiva",
  LAVAN: "Lavan",
  LOWA: "Lowa",
  MAD_ROCK: "Mad Rock",
  MILLET: "Millet",
  OCUN: "Ocun",
  RED_CHILI: "Red Chili",
  SALTIC: "Saltic",
  SCARPA: "Scarpa",
  SIMOND: "Simond",
  SNAKE: "Snake",
  SO_ILL: "So iLL",
  TENAYA: "Tenaya",
  TRIOP: "Triop",
  TULSON_TOLF: "Tulson Tolf",
  UNPARALLEL: "Unparallel",
  WILD_CLIMB: "Wild Climb",
} as const;
type Brand = (typeof BRANDS)[keyof typeof BRANDS];

const SHOES: Record<Brand, string[]> = {
  [BRANDS.ACOPA]: [
    "SPECTRE",
    "SHOT",
    "NOVA LACES",
    "NOVA",
    "MERLIN",
    "LEGEND",
    "JB",
    "GAMA",
    "FLY",
    "ENZO",
    "CHAMELEON",
    "B3",
    "AZTEC",
  ],
  [BRANDS.ALPIDEX]: [],
  [BRANDS.ASAKUSA]: [],
  [BRANDS.BLACK_DIAMOND]: [
    "Zone LV",
    "Zone",
    "Shadow LV",
    "Shadow",
    "Session",
    "Momentum Lace",
    "Momentum",
    "Method S",
    "Method",
    "Focus",
    "Aspect Pro",
    "Aspect",
  ],
  [BRANDS.BOREAL]: [
    "Synergy",
    "Silex",
    "Satori",
    "Ninja",
    "Mutant",
    "Joker Plus",
    "Joker Lace",
    "Joker",
    "Diabolo",
    "Diabola",
    "Dharma",
    "Crux Lace",
    "Crux",
    "Beta Eco",
    "Beta",
    "Ballet",
    "Alpha",
    "Ace",
  ],
  [BRANDS.BUTORA]: [
    "New Bora",
    "Mantra",
    "Habara",
    "Gomi Spider",
    "Endeavor",
    "Brava",
    "Altura",
    "Acro Comp",
  ],
  [BRANDS.CLIMB_X]: [],
  [BRANDS.CYPHER]: [],
  [BRANDS.EB]: [
    "Torch Lace 3.0",
    "Strange",
    "Red",
    "Neo Kid",
    "Nebula",
    "Mojo",
    "Jarvis Velcro",
    "Jarvis Lace",
    "Guardian",
    "Electron",
    "Django 3.0",
    "Black Opium",
    "Balboa",
  ],
  [BRANDS.EVOLV]: [
    "Zenist Pro LV",
    "Zenist Pro",
    "Zenist",
    "Yosemite Bum LV",
    "Yosemite Bum",
    "Venga",
    "V6",
    "Titan",
    "The General",
    "Shaman Pro LV",
    "Shaman Pro",
    "Shaman LV",
    "Shaman Lace LV",
    "Shaman Lace",
    "Shaman",
    "Shaktra",
    "Rave",
    "Phantom LV",
    "Phantom",
    "Kronos",
    "Kira",
    "Geshido Lace",
    "Geshido",
    "Elektra Lace",
    "Elektra",
    "Eldo Z",
    "Defy Lace",
    "Defy",
  ],
  [BRANDS.FIVE_TEN]: [
    "Rogue VCS",
    "Quantum VCS",
    "Niad VCS",
    "Niad Moccasym",
    "Niad Lace",
    "Kirigami",
    "Hiangle Pro",
    "Hiangle",
    "Grandstone",
    "Crawe",
    "Asym",
    "Anasazi VCS",
    "Anasazi",
    "Aleon",
  ],
  [BRANDS.GARRA]: ["Sensei", "Kyoso", "Kokoro", "Kamae"],
  [BRANDS.JURAX]: [],
  [BRANDS.LA_SPORTIVA]: [
    "Zenit",
    "Theory",
    "Testarossa",
    "Tarantulace",
    "Tarantula Boulder",
    "Tarantula",
    "TC Pro",
    "Stickit",
    "Speedster",
    "Solution Comp",
    "Solution",
    "Skwama Vegan",
    "Skwama",
    "Python",
    "Otaki",
    "Ondra Comp",
    "Mythos Eco",
    "Mythos",
    "Mistral",
    "Miura VS",
    "Miura",
    "Mega Ice Evo",
    "Mandala",
    "Mantra",
    "Kubo",
    "Kataki",
    "Katana Lace",
    "Katana",
    "Gripit",
    "Genius",
    "Futura",
    "Finale",
    "Cobra Eco",
    "Cobra 4:99",
    "Cobra 4.99",
    "Cobra",
    "Aragon",
  ],
  [BRANDS.LAVAN]: [],
  [BRANDS.LOWA]: [],
  [BRANDS.MAD_ROCK]: [
    "Weaver",
    "Shark 3.0",
    "Shark 2.0",
    "Rover",
    "Remora Tokyo",
    "Remora LV",
    "Remora HV",
    "Remora",
    "Redline Strap",
    "Redline Lace",
    "Pulse Positive",
    "Pulse Negative",
    "Phoenix",
    "M5",
    "Lyra",
    "Lotus",
    "Haywire",
    "Flash 2.0",
    "Drifter",
    "Drone LV Black",
    "Drone LV",
    "Drone HV Black",
    "Drone HV",
    "Drone CS LV",
    "Drone CS HV",
    "Drone Comp LV",
    "Drone Comp HV",
    "Demon 2.0",
    "Badger",
    "Agama",
  ],
  [BRANDS.MILLET]: ["SIURANA EVO", "ROCK UP EVO", "EASY UP"],
  [BRANDS.OCUN]: [
    "Voltage LV",
    "Voltage 2",
    "Striker QC",
    "Striker LU",
    "Sigma",
    "Rivalry",
    "Ribbit",
    "Rental",
    "Pearl 20th Anniversary",
    "Pearl",
    "Ozone HV",
    "Ozone",
    "Oxi Lu",
    "Jett QC",
    "Jett LU",
    "Jett Crack",
    "Iris",
    "Havoc",
    "Fury",
    "Diamond",
    "Bullit",
    "Advancer QC",
    "Advancer LU",
  ],
  [BRANDS.RED_CHILI]: [
    "Voltage Lace",
    "Voltage LV",
    "Voltage 2",
    "Session Air",
    "Session 4 S",
    "Session",
    "Sausalito",
    "Pulpo",
    "Puzzle",
    "Mystix",
    "Fusion LV",
    "Fusion",
    "Circuit LV",
    "Circuit",
    "Ventic Air Lace",
    "Sensor",
  ],
  [BRANDS.SALTIC]: [],
  [BRANDS.SCARPA]: [
    "Velocity",
    "Veloce Lace",
    "Veloce",
    "Vapor V",
    "Vapor S",
    "Vapor",
    "Reflex V",
    "Reflex",
    "Quantix SF",
    "Quantic",
    "Origin",
    "Mago",
    "Maestro Mid Eco",
    "Maestro Eco",
    "Maestro Alpine",
    "Jungle",
    "Instinct VSR",
    "Instinct VS",
    "Instinct SR",
    "Instinct",
    "Helix",
    "Generator Mid",
    "Generator",
    "Force V",
    "Force",
    "Furia S",
    "Furia Air",
    "Drago LV",
    "Drago",
    "Chimera",
    "Boostic",
    "Booster",
    "Arpia",
  ],
  [BRANDS.SIMOND]: [
    "VERTIKA SOFT",
    "VERTIKA",
    "Klimb",
    "EDGE SOFT",
    "EDGE SLIPPER",
    "EDGE LACES",
  ],
  [BRANDS.SNAKE]: [],
  [BRANDS.SO_ILL]: [
    "The Street",
    "The Runner LV",
    "The Runner",
    "The Onset",
    "Street LV",
    "Street",
    "New Zero",
    "Momoa Pro LV",
    "Momoa Pro",
    "Free Range Pro",
    "Free Range LV",
    "Free Range",
    "Catch",
  ],
  [BRANDS.TENAYA]: [
    "Tanta LX",
    "Tanta Laces",
    "Tanta",
    "Tatanka",
    "Tarifa",
    "Ra",
    "Oasi LV",
    "Oasi",
    "Mundaka",
    "Mastia",
    "Masai",
    "Lati",
    "Inti",
    "Indalo",
    "Iati",
    "Aqua+",
    "Arai",
  ],
  [BRANDS.TRIOP]: [
    "TRITOP",
    "TIGER TOP",
    "TANTRUM",
    "TANGO LADY",
    "TANGO",
    "START",
    "RENTAL VCR",
    "RAP",
    "PHET MAAK VCR",
    "PHET MAAK",
    "ORCA",
    "JUNIOR",
    "GENUS VCR",
    "GENUS",
    "CONGA GREEN",
  ],
  [BRANDS.TULSON_TOLF]: [
    "UTAH",
    "Trad Xhard",
    "Trad Velcro",
    "Trad Laces",
    "Trad Invernal",
    "Step 2",
    "Step 1",
    "Qubit Invernal",
    "Qubit",
    "OUT",
    "IN",
    "Grade Velcro",
    "Grade Laces",
    "Grade Indoor",
    "California",
  ],
  [BRANDS.UNPARALLEL]: [
    "Vim",
    "Vega",
    "UP Rise Zero VCS LV",
    "UP Rise VCS LV",
    "UP Rise VCS",
    "UP Rise Pro",
    "UP Pivot",
    "UP Mocc",
    "UP Lace LV",
    "UP Lace",
    "UP Duel",
    "TN Pro LV",
    "TN Pro",
    "Souped UP",
    "Sirius Lace LV",
    "Sirius Lace",
    "Regulus LV",
    "Regulus",
    "Newtro VCS",
    "Newtro Lace",
    "Lyra",
    "Leopard II",
    "Leopard 2",
    "Hold Up VCS",
    "Hold Up Slipper",
    "Grade Mocc",
    "Grade Engage",
    "Flagship LV",
    "Flagship",
    "Engage VCS LV",
    "Engage VCS",
    "Engage Lace UP",
  ],
  [BRANDS.WILD_CLIMB]: [
    "Sky V",
    "Sky Laces",
    "Pegaso",
    "Pantera V",
    "Pantera Soft",
    "Pantera Laser",
    "Pantera 2.0",
    "Pantera",
    "Mangusta",
    "Gladiator",
    "First Step",
    "Dagara",
    "Bat",
  ],
};

export = { BRANDS, SHOES };
